[build]
  publish = "src"

# Remove these function configurations since you're not using serverless functions
# [functions]
#  directory = "netlify/functions"
#  node_bundler = "esbuild"

# Replace the current redirect with these:
# First - Try to serve files directly
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Second - Fallback to SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false